Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -10,6 +10,11 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+      - name: Check encoded string length
+        run: echo "${{ secrets.KEYSTORE_BASE_64 }}" | wc -c
+      - name: Create keystore directory
+        run: mkdir -p keystore
+
       - name: Decode Keystore
         id: decode_keystore
         uses: timheuer/base64-to-file@v1
@@ -17,4 +22,4 @@ jobs:
           fileName: 'keystore/keystore.jks'
           encodedString: ${{ secrets.KEYSTORE_BASE_64 }}
       - name: List files
-        run: ls -la 
+        run: ls -la keystore || echo "Failed to list files. Directory might not exist."
